### ISSUE TITLE
Current security issues.

### ISSUE THREAD

**Issue by JMHenri** [braitsch/node-login#48]
There are a few fixes that need to be fixed either in here or on your own if you are someone who is looking to use this code.

1. The delete account method does not check for authorization, so you can delete anybodies account.
2. The reset-password logic is also abusable in the same way, many of the calls are, go thru and fix at your own discretion.
3. Make sure to code in some xsrf tokens or cors rulings. These methods are susceptible to cross-site request forgeries.

**Comment by braitsch** [comment]
Feel free to submit a pull request.

**Comment by Azewilous** [comment]
possibly creating a verification function that forces the user re-enter their password before making such account modifications, or maybe session sharing if that's what your looking for.

**Comment by braitsch** [comment]
@JMHenri 1/ The delete account method now uses the logged in user's session id instead of data contained in the POST request. 2/ The reset-password link now contains a UUID which is used to lookup the account and then the request is validated against the user's last recorded IP address. Aside from these changes what else would you suggest?

**Comment by SCG82** [comment]
A more secure password hashing algorithm: #52
